### ISSUE TITLE
create new datapack feature out of order

### ISSUE THREAD

**Issue by DeepVoyager111** [JoachimCoenen/Datapack-Editor#30]
when i create new datapack this happens
![image](https://user-images.githubusercontent.com/78071019/220111402-bc03a32c-c896-4a4e-9a72-073274cdf162.png)

**Comment by JoachimCoenen** [comment]
should be fixed with [v0.5.0-alpha](https://github.com/JoachimCoenen/Datapack-Editor/releases/tag/v0.5.0-alpha)
