### ISSUE TITLE
DatapackEditor_v0.8.5-alpha_windows.zip is detected as virus by Windows Defender

### ISSUE THREAD

**Issue by IrrelevantGaymer** [JoachimCoenen/Datapack-Editor#51]
When downloading the zip file for the latest release (0.8.5-alpha at the time) for windows, Windows Defender flags the folder as a virus

**Comment by JoachimCoenen** [comment]
It has been built on Linux using wine. I'll have to properly rebuild it on windows then. 
In the meantime v0.8.0 should (hopefully) not be flagged as a virus.

**Comment by JoachimCoenen** [comment]
This seems to be a longstanding problem with pyinstaller https://stackoverflow.com/questions/43777106

**Comment by JoachimCoenen** [comment]
hopefully fixed with 0.8.6-alpha
